export enum BbtStatus {
  SUCIO = 'SUCIO',
  LIMPIO = 'LIMPIO',
  SANITIZADO = 'SANITIZADO',
  DISPONIBLE = 'DISPONIBLE',
  EN_MADURACION = 'EN_MADURACION',
  EN_CARBONATACION = 'EN_CARBONATACION',
  LISTO_PARA_EMPAQUE = 'LISTO_PARA_EMPAQUE',
}